server:
  port: 8001

spring:
  application:
    name: provider-payment-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment-hystrix8001
