server:
  port: 80

spring:
  application:
    name: consumer-feign-hystrix-order80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true
